# Generated by Django 4.2 on 2023-04-18 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('body', models.CharField(max_length=30)),
                ('create_at', models.DateField()),
                ('author', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_value', models.CharField(choices=[('Likes', 'Likes'), ('Dislike', 'Dislike')], max_length=20)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweeter.tweet')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweeter.tweet')),
            ],
        ),
    ]
